### ISSUE TITLE
Что-то сбилось с обновлением.

### ISSUE THREAD

**Issue by githubjeka** [getjump/ru-php-the-right-way#47]
На оф. сайте что-то не то берётся
http://getjump.github.io/ru-php-the-right-way/

![image](https://cloud.githubusercontent.com/assets/874234/6787825/541d1c6e-d1a6-11e4-84f1-3fb6c85f297b.png)

А форке обновлённое
![image](https://cloud.githubusercontent.com/assets/874234/6787834/6280d890-d1a6-11e4-84ac-73612313e33a.png)

**Comment by getjump** [comment]
Поправил
