### ISSUE TITLE
GIT Books

### ISSUE THREAD

**Issue by littleguga** [getjump/ru-php-the-right-way#55]
How about publishing this book on gitbooks.io?

**Comment by littleguga** [comment]
По привычке на англ написал.

Собственно, если автор перевода не против — опубликовать данную книгу в gitbooks.io? Я могу этим заняться, если дадите добро.

**Comment by getjump** [comment]
@littleguga Я не против

**Comment by littleguga** [comment]
Что-то я недооценил задачу, слишком много менять и переписывать. Лучше оставить так, как есть.
