### ISSUE TITLE
Опечатки в блоке "Пространства имен" на главной странице и одно улучшение

### ISSUE THREAD

**Issue by SamoilenkoEvgeniy** [getjump/ru-php-the-right-way#62]
"который призван обеспечить стандарты для описания файлов, классов и пространств имен, что позволяет создавать **PnP код.**"
наверное php?

ссылку на github в блоке "Как внести вклад" лучше сделать с target="_blank", удобнее это просмотреть в новом окне.

Спасибо!

**Comment by chlp** [comment]
Про target="_blank" не совсем согласен. С одной стороны удобней, с другой стороны:
1) браузер предоставляет эту возможность;
2) тогда и все остальные ссылки нужно делать target="_blank";
3) https://habrahabr.ru/post/282880/.
