### ISSUE TITLE
404 (Руководство по написанию кода)

### ISSUE THREAD

**Issue by batFormat** [getjump/ru-php-the-right-way#67]
В разделе, **Стандарты написания кода** не рабочие ссылки.
http://pear.php.net/manual/ru/standards.php
https://framework.zend.com/wiki/display/ZFDEV2/Coding+Standards

**Comment by pavelblossom** [comment]
Корректная ссылка на PEAR:
http://pear.php.net/manual/en/ - сейчас есть только на английском.
Zend 3 поддерживает PHP-FIG стандарт:
https://www.php-fig.org
